version: "3"

services:
  repair-shop:
    image: repair-shop:latest
    restart: always
    networks:
      - repair-shop-network
    depends_on:
      - database
    ports:
      - 8080:8080

  database:
    image: mysql:8
    restart: always
    networks:
      - repair-shop-network
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=repair_shop_db
    ports:
      - 3306:33060
    volumes:
      - db-data:/var/lib/mysql

networks:
  repair-shop-network:

volumes:
  db-data: